spring.application.name=apitoken

spring.datasource.url=jdbc:mysql://localhost:3306/sprint_apitoken
spring.datasource.username=root
spring.datasource.password=loco1727
spring.jpa.hibernate.ddl-auto=update

#  Credenciales por defecto para autenticación básica - temporalmente
spring.security.user.name=admin
spring.security.user.password=admin123

